#!/bin/bash

echo "Stashing changes not staged for commit."
git stash --keep-index --quiet
FILES=$(git diff --staged --name-status | egrep "*\.h$|*\.cpp$" | cut -f 2)
RESULT=0
if [ -n "$FILES" ]; then
	clang-tidy -p build/ --config-file .clang-tidy $FILES
	RESULT=$?
fi
echo "Pop previously created stash."
git stash pop --quiet
exit $RESULT
