// NOLINTBEGIN(cppcoreguidelines-macro-usage)

X(QtdId,          uuid,      UuidRole)
X(QString,        title,     Qt::DisplayRole)
X(Task::Status,   status,    ActiveRole)
X(QDateTime,      start,     StartRole)
X(QDateTime,      due,       DueRole)
X(QDateTime,      resolve,   ResolveRole)
X(QString,        plainText, PlainTextRole)
X(QString,        richText,  RichTextRole)
X(QVariantList,   tags,      TagsRole)

// NOLINTEND(cppcoreguidelines-macro-usage)